### ISSUE TITLE
test file in routes directory causes error

### ISSUE THREAD

**Issue by lwhiteley** [lerna/getting-started-example#2]
test file in routes directory causes error when running the remix example

```bash
ReferenceError: test is not defined
    at Object.<anonymous> (/dev/getting-started-example/packages/remixapp/app/routes/example.spec.tsx:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /dev/getting-started-example/packages/remixapp/node_modules/@remix-run/serve/index.js:43:17
    at Layer.handle [as handle_request] (/dev/getting-started-example/packages/remixapp/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by JamesHenry** [comment]
Thanks @lwhiteley, I'm just taking over this repo now. It looks like this was resolved at some point, so closing
